using System;
using System.Reflection;
using HarmonyLib;
using RimWorld;
using UnityEngine;
using Verse;

namespace RimTalkQuests
{
    /// <summary>
    /// Main mod class for RimTalk-Quests
    ///
    /// This mod is a derivative work based on RimTalk by juicy, licensed under CC BY-NC-SA 4.0.
    /// It reuses RimTalk's AI model configuration and API calling functionality to generate
    /// dynamic quest descriptions.
    /// </summary>
    [StaticConstructorOnStartup]
    public class RimTalkQuestsMod : Mod
    {
        public static RimTalkQuestsMod Instance { get; private set; }
        public static Harmony HarmonyInstance { get; private set; }
        public static QuestSettings Settings { get; private set; }

        public RimTalkQuestsMod(ModContentPack content) : base(content)
        {
            Instance = this;
            Settings = GetSettings<QuestSettings>();

            Log.Message("[RimTalk-Quests] Initializing...");

            // Check if RimTalk is loaded
            if (!ModsConfig.IsActive("cj.rimtalk"))
            {
                Log.Error(
                    "[RimTalk-Quests] RimTalk is not loaded! This mod requires RimTalk to function."
                );
                return;
            }

            try
            {
                // Apply Harmony patches
                HarmonyInstance = new Harmony("rimtalk.quests");
                HarmonyInstance.PatchAll(Assembly.GetExecutingAssembly());

                Log.Message(
                    "[RimTalk-Quests] Successfully initialized with Harmony patches applied."
                );
                Log.Message(
                    "[RimTalk-Quests] Attribution: Based on RimTalk by juicy (CC BY-NC-SA 4.0)"
                );
            }
            catch (Exception ex)
            {
                Log.Error($"[RimTalk-Quests] Failed to initialize: {ex}");
            }
        }

        public override string SettingsCategory()
        {
            return "RimTalk - Quests";
        }

        public override void DoSettingsWindowContents(Rect inRect)
        {
            base.DoSettingsWindowContents(inRect);
            Listing_Standard listingStandard = new Listing_Standard();
            listingStandard.Begin(inRect);

            listingStandard.CheckboxLabeled(
                "Enable AI Quest Descriptions",
                ref Settings.enableAIDescriptions,
                "When enabled, quest descriptions will be generated by AI using RimTalk's configuration."
            );

            listingStandard.CheckboxLabeled(
                "Cache Generated Descriptions",
                ref Settings.cacheDescriptions,
                "Cache AI-generated descriptions to avoid regenerating the same quest descriptions."
            );

            listingStandard.CheckboxLabeled(
                "Verbose Debug Logging",
                ref Settings.verboseDebugLogging,
                "Enable detailed debug logs including streaming chunks. Only works in Dev Mode."
            );

            listingStandard.Gap();
            listingStandard.Label("Custom Quest Instruction:");
            listingStandard.Label(
                "Leave empty to use default. This will be appended to RimTalk's base instruction.",
                -1f
            );

            float textHeight = 150f;
            Rect textAreaRect = listingStandard.GetRect(textHeight);
            Settings.customQuestInstruction = string.IsNullOrWhiteSpace(
                Settings.customQuestInstruction
            )
                ? Constant.GetDefaultQuestInstruction()
                : Settings.customQuestInstruction;
            Settings.customQuestInstruction = Widgets.TextArea(
                textAreaRect,
                Settings.customQuestInstruction
            );

            listingStandard.Gap();

            if (listingStandard.ButtonText("Clear Cache"))
            {
                Services.QuestDescriptionGenerator.ClearCache();
                Messages.Message(
                    "Quest description cache cleared.",
                    MessageTypeDefOf.NeutralEvent,
                    historical: false
                );
            }

            listingStandard.Gap();
            listingStandard.Label("RimTalk-Quests uses your existing RimTalk AI configuration.");
            listingStandard.Label(
                $"Currently processing: {Services.QuestDescriptionGenerator.ProcessingCount} quests"
            );

            listingStandard.End();
        }
    }

    public class QuestSettings : ModSettings
    {
        public bool enableAIDescriptions = true;
        public bool cacheDescriptions = true;
        public bool verboseDebugLogging = false;
        public string customQuestInstruction = "";

        public override void ExposeData()
        {
            base.ExposeData();
            Scribe_Values.Look(ref enableAIDescriptions, "enableAIDescriptions", true);
            Scribe_Values.Look(ref cacheDescriptions, "cacheDescriptions", true);
            Scribe_Values.Look(ref verboseDebugLogging, "verboseDebugLogging", false);
            Scribe_Values.Look(ref customQuestInstruction, "customQuestInstruction", "");
        }
    }
}
